name: Build & Publish Release APK

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Make Gradle executable
      run: chmod +x ./gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease
      
    - name: Debug - Print working directory
      run: |
        pwd
        ls -la
        
    - name: Releasing using Hub
      uses: sangatdesai/release-apk@main
      env:
        GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        APP_FOLDER: app
